# Generated by Django 5.2.7 on 2025-10-14 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0007_alter_lesson_options_lesson_order'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
